name: Webhook Test

on:
  repository_dispatch:
    types:
      - hello

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hello
        if: github.event.action == 'hello'
        run: |
          echo test666
