name: testAction

on:
  repository_dispatch:
    types:
      - helloworld

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        if: github.event.action == "helloworld"
        run: echo Hello world!
